pub fn category_name_for_group_id(id: u8) -> &'static str {
  match id {
    1 => "tv_shows",
    2 => "world_news",
    3 => "lifestyle_fashion",
    4 => "sports",
    5 => "news_current_affairs",
    6 => "food_drink",
    7 => "opinion_analysis",
    8 => "technology",
    9 => "education",
    10 => "culture_arts",
    11 => "lifestyle_entertainment",
    12 => "business_economy",
    13 => "auto",
    14 => "regional_news",
    15 => "entertainment_humor",
    16 => "family_parenting",
    17 => "lifestyle_diy",
    18 => "shopping_deals",
    19 => "beauty_health",
    20 => "politics",
    21 => "entertainment_celebrities",
    22 => "travel",
    23 => "health",
    24 => "health_wellness",
    25 => "local_news",
    26 => "law_justice",
    27 => "society",
    28 => "science_nature",
    29 => "lifestyle_advice",
    30 => "media",
    31 => "weather",
    32 => "lifestyle_home",
    _ => "misc",
  }
}
